#!/bin/sh

unset SESSION_MANAGER
exec /etc/X11/xinit/xinitrc

i3wm &

# Load general vnc settings
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &

