#!/bin/sh

DE="KDE"

unset SESSION_MANAGER
exec /etc/X11/xinit/xinitrc

# Load overall settings
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

case "$DE" in
  "KDE")
    startkde &;;
  "GNOME")
    gnome-session &;;
esac
