#!/bin/sh

#unset SESSION_MANAGER

# Load general vnc settings
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

gnome-session --session=gnome-classic &
